Repository HZ-HBO-ICT/it-conference, pull requests merged in 2023-08, with the labels that each got.

#70 Add a docs directory
  docs/db-diagram.drawio
Labels: documentation

#68 Rework/faq
  resources/views/faq.blade.php
Labels: enhancement

#73 Fix the footer spacing
  resources/views/layouts/app.blade.php
Labels: bugfix

#74 Frontend/font
  resources/css/app.css
  resources/fonts/Inter-Var.ttf
  tailwind.config.js
Labels: enhancement

#63 Feature - Schedule Management
  app/Http/Controllers/RoomController.php
  app/Http/Controllers/ScheduleController.php
  app/Http/Controllers/TimeslotController.php
  app/Http/Livewire/ResetTimeslots.php
  app/Http/Livewire/RoomAndTimeslotSelector.php
  app/Models/Presentation.php
  app/Models/Timeslot.php
  app/View/Components/ScheduleBlock.php
  database/factories/PresentationFactory.php
  database/factories/SpeakerFactory.php
  database/seeders/DatabaseSeeder.php
  database/seeders/ParticipantSeeder.php
  resources/views/components/schedule-block.blade.php
  resources/views/livewire/reset-timeslots.blade.php
  resources/views/livewire/room-and-timeslot-selector.blade.php
  resources/views/moderator/schedule/index.blade.php
  resources/views/moderator/schedule/presentation-schedule.blade.php
  resources/views/moderator/schedule/presentations-for-scheduling.blade.php
  resources/views/moderator/schedule/timeslots-create.blade.php
  routes/web.php
Labels: enhancement, High Priority

#72 Fix - Companies can request after approval
  resources/views/teams/requests.blade.php
  resources/views/teams/show.blade.php
Labels: bugfix

#77 Fix - Content moderator dashboard
  app/Http/Controllers/ContentModeratorController.php
  app/Providers/AppServiceProvider.php
  app/View/Components/ContentModeratorBlock.php
  app/View/Components/ContentModeratorLayout.php
  app/View/Components/ContentModeratorOverviewBlock.php
  app/View/Components/SidebarLink.php
  resources/views/components/content-moderator-block.blade.php
  resources/views/components/content-moderator-overview-block.blade.php
  resources/views/components/pagination.blade.php
  resources/views/components/sidebar-link.blade.php
  resources/views/idkthename.blade.php
  resources/views/layouts/content-moderator.blade.php
  resources/views/livewire/auth-navigation-menu.blade.php
  resources/views/moderator/details/booth.blade.php
  resources/views/moderator/details/presentation.blade.php
  resources/views/moderator/details/sponsorship.blade.php
  resources/views/moderator/details/team.blade.php
  resources/views/moderator/overview.blade.php
  resources/views/moderator/requests/booths.blade.php
  resources/views/moderator/requests/presentations.blade.php
  resources/views/moderator/requests/sponsorships.blade.php
  resources/views/moderator/requests/teams.blade.php
  routes/web.php
Labels: enhancement, High Priority

#78 Feature - Content moderator can manually add companies
  app/Actions/Jetstream/CreateTeam.php
  app/Http/Controllers/InvitationController.php
  app/Mail/InviteCompany.php
  app/Policies/TeamPolicy.php
  resources/views/auth/company-rep-invitation.blade.php
  resources/views/emails/invite-company-rep.blade.php
  resources/views/teams/create-team-form.blade.php
  resources/views/teams/create.blade.php
  routes/web.php
Labels: enhancement

#83 Feature/contact page
  resources/views/contact.blade.php
  resources/views/faq.blade.php
  resources/views/livewire/auth-navigation-menu.blade.php
  resources/views/livewire/guest-navigation-menu.blade.php
  routes/web.php
Labels: enhancement

#75 Error pages
  resources/views/errors/401.blade.php
  resources/views/errors/403.blade.php
  resources/views/errors/404.blade.php
  resources/views/errors/500.blade.php
  resources/views/errors/minimal.blade.php
Labels: enhancement

#99 Feature/companies page
  app/Http/Controllers/TeamsController.php
  resources/views/companies.blade.php
  resources/views/livewire/auth-navigation-menu.blade.php
  resources/views/livewire/guest-navigation-menu.blade.php
  routes/web.php
  tailwind.config.js
Labels: enhancement

#90 Fix - Registration details
  app/Actions/Fortify/CreateNewUser.php
  app/Actions/Jetstream/CreateTeam.php
  app/Actions/Jetstream/InviteTeamMember.php
  app/Actions/Jetstream/UpdateTeamName.php
  app/Models/Team.php
  app/Models/User.php
  database/factories/TeamFactory.php
  database/factories/UserFactory.php
  database/migrations/2023_07_05_123637_update_teams_table_with_fields_for_company_data.php
  database/migrations/2023_08_23_225110_update_user_with_institution_name.php
  resources/views/auth/register.blade.php
  resources/views/teams/create-team-form.blade.php
  tests/Feature/CreateTeamTest.php
  tests/Feature/DeleteTeamTest.php
  tests/Feature/RegistrationTest.php
Labels: bugfix

#92 Feature - Allow profile picture and logo upload
  app/Http/Livewire/ManageCompanyLogo.php
  app/Models/Team.php
  config/jetstream.php
  database/migrations/2023_08_24_221851_update_teams_table_with_logo_path.php
  resources/views/livewire/manage-company-logo.blade.php
  resources/views/teams/show.blade.php
Labels: enhancement
