Repository HZ-HBO-ICT/it-conference, pull requests merged in 2023-10, with the labels that each got.

#269 Fixed copy of storage dir in stato deployment script
  .github/workflows/deploy.yml
Labels: high priority, bugfix, production

#281 Fix - Size of logos on companies page
  resources/views/companies.blade.php
Labels: high priority, bugfix

#286 Development
  app/Http/Controllers/ContentModerator/BoothController.php
  app/Http/Controllers/ContentModerator/CompanyController.php
  app/Http/Controllers/ContentModerator/PresentationController.php
  app/Http/Controllers/ContentModerator/RoomController.php
  app/Http/Controllers/ContentModerator/SponsorshipController.php
  app/Http/Controllers/ContentModeratorController.php
  app/Models/Booth.php
  app/Models/User.php
  resources/views/companies.blade.php
  resources/views/components/action-section.blade.php
  resources/views/components/button-link.blade.php
  resources/views/components/details-list-item.blade.php
  resources/views/components/details-panel.blade.php
  resources/views/components/input-textarea.blade.php
  resources/views/components/list-section-item.blade.php
  resources/views/components/list-section.blade.php
  resources/views/components/pagination.blade.php
  resources/views/components/select.blade.php
  resources/views/components/sidebar-link-content-mod.blade.php
  resources/views/components/sidemenus/content-moderator.blade.php
  resources/views/moderator/booths/create.blade.php
  resources/views/moderator/booths/index.blade.php
  resources/views/moderator/booths/show.blade.php
  resources/views/moderator/companies/create.blade.php
  resources/views/moderator/companies/index.blade.php
  resources/views/moderator/companies/show.blade.php
  resources/views/moderator/presentations/index.blade.php
  resources/views/moderator/presentations/show.blade.php
  resources/views/moderator/rooms/create.blade.php
  resources/views/moderator/rooms/index.blade.php
  resources/views/moderator/rooms/show.blade.php
  resources/views/moderator/sponsors/index.blade.php
  resources/views/moderator/sponsors/show.blade.php
  resources/views/teams/create-team-form.blade.php
  routes/web.php
Labels: bugfix, production

#232 UI/UX: rework company dashboard
  resources/views/components/company-dashboard-section.blade.php
  resources/views/livewire/booth-request.blade.php
  resources/views/livewire/sponsorship-request.blade.php
Labels: high priority, ui/ux

#302 Fix - sponsor cards on the main page
  resources/views/welcome.blade.php
Labels: high priority, bugfix

#292 Rework - Remove schedule lunch break
  app/Http/Controllers/ScheduleController.php
  app/Http/Controllers/TimeslotController.php
  app/Models/Room.php
  database/factories/PresentationFactory.php
  resources/views/moderator/schedule/timeslots-create.blade.php
Labels: bugfix

#303 Fix security issues with an npm package
  package-lock.json
Labels: high priority, bugfix, production

#300 Feature/295 company applications
  resources/views/moderator/companies/show.blade.php
  resources/views/moderator/sponsors/show.blade.php
Labels: enhancement, high priority, bugfix

#289 Fix some of the links on the content mod homepage
  app/View/Components/ContentModeratorBlock.php
  resources/views/components/content-moderator-block.blade.php
  resources/views/components/content-moderator-dashboard.blade.php
Labels: high priority, bugfix

#310 Release Friday 13-10-2023
  app/Http/Controllers/ScheduleController.php
  app/Http/Controllers/TimeslotController.php
  app/Models/Room.php
  app/View/Components/ContentModeratorBlock.php
  database/factories/PresentationFactory.php
  package-lock.json
  resources/views/components/company-dashboard-section.blade.php
  resources/views/components/content-moderator-block.blade.php
  resources/views/components/content-moderator-dashboard.blade.php
  resources/views/livewire/booth-request.blade.php
  resources/views/livewire/sponsorship-request.blade.php
  resources/views/moderator/companies/show.blade.php
  resources/views/moderator/schedule/timeslots-create.blade.php
  resources/views/moderator/sponsors/show.blade.php
  resources/views/welcome.blade.php
Labels: enhancement, dependencies, bugfix, production

#312 Hotfix - Push presentation request/edit deadline to 27th of October
  app/Models/Presentation.php
  app/Policies/PresentationPolicy.php
Labels: high priority, bugfix

#318 Development
  app/Models/Presentation.php
  app/Policies/PresentationPolicy.php
Labels: high priority, bugfix, production

#317 Fix - Negative max participants
  app/Http/Controllers/PresentationController.php
  app/Http/Livewire/EditPresentationModal.php
  app/Models/Presentation.php
Labels: bugfix

#309 Fix - Issue when creating a booth with empty additional info
  app/Http/Controllers/ContentModerator/BoothController.php
Labels: bugfix

#322 Feature - front facing company page
  app/Http/Controllers/TeamsController.php
  resources/views/companies.blade.php
  resources/views/teams/public/show.blade.php
  routes/web.php
Labels: high priority, ui/ux

#329 UI/UX - Added gradient background on basic pages
  resources/views/companies.blade.php
  resources/views/contact.blade.php
  resources/views/faq.blade.php
  resources/views/speakers/index.blade.php
  resources/views/teams/public/show.blade.php
Labels: enhancement, ui/ux

#331 Fix - sponsors in mobile version of the main page
  resources/views/welcome.blade.php
Labels: bugfix

#333 Fix - Presentation create for company
  app/Console/Commands/AddSpeakerToPresentation.php
  app/Http/Controllers/ContentModerator/PresentationController.php
  resources/views/moderator/presentations/create.blade.php
Labels: bugfix

#334 Feature - sign up for presentations
  app/Http/Controllers/ContentModerator/ContentModeratorController.php
  app/Http/Controllers/ContentModerator/ScheduleController.php
  app/Http/Controllers/EnrollmentController.php
  app/Http/Controllers/HubController.php
  app/Http/Controllers/PresentationController.php
  app/Http/Controllers/ProgrammeController.php
  app/Http/Controllers/TeamsController.php
  app/Http/Livewire/RoomAndTimeslotSelector.php
  app/Models/Presentation.php
  app/Policies/PresentationPolicy.php
  app/View/Components/EnrollModal.php
  resources/views/components/enroll-modal.blade.php
  resources/views/components/schedule-block.blade.php
  resources/views/layouts/hub.blade.php
  resources/views/myhub/programme.blade.php
  resources/views/presentations/create.blade.php
  resources/views/presentations/show.blade.php
  resources/views/programme/index.blade.php
  resources/views/programme/show.blade.php
  resources/views/speakers/presentation/show.blade.php
  resources/views/teams/public/index.blade.php
  routes/web.php
  tests/Feature/EnrollmentTest.php
Labels: enhancement, high priority
