Repository HZ-HBO-ICT/it-conference, pull requests merged in 2023-11, with the labels that each got.

#343 Hotfix - company details page design
  resources/views/programme/show.blade.php
  resources/views/teams/public/show.blade.php
Labels: bugfix, ui/ux

#346 Development
  resources/views/programme/show.blade.php
  resources/views/teams/public/show.blade.php
Labels: bugfix, production

#348 Hotfix - Schedule
  app/Console/Commands/ModifyTimeslotDuration.php
  app/Http/Controllers/ContentModerator/ScheduleController.php
  app/Http/Controllers/HubController.php
  app/Http/Controllers/ProgrammeController.php
  app/Http/Controllers/TimeslotController.php
  app/Http/Livewire/RoomAndTimeslotSelector.php
  public/img/keynote.png
  resources/views/moderator/presentations/show.blade.php
  resources/views/moderator/schedule/index.blade.php
  resources/views/myhub/programme.blade.php
  resources/views/presentations/show.blade.php
  resources/views/programme/index.blade.php
  resources/views/speakers/index.blade.php
Labels: high priority, bugfix
