Repository HZ-HBO-ICT/it-conference, pull requests merged in 2023-09, with the labels that each got.

#125 Ux rework/content management dashboard
  app/Http/Responses/LoginResponse.php
  app/Providers/FortifyServiceProvider.php
  app/View/Components/AppModeratorLayout.php
  app/View/Components/ContentModeratorBlock.php
  app/View/Components/ContentModeratorOverviewBlock.php
  app/View/Components/SidebarLinkContentMod.php
  resources/views/components/content-moderator-block.blade.php
  resources/views/components/content-moderator-overview-block.blade.php
  resources/views/components/sidebar-link-content-mod.blade.php
  resources/views/layouts/app-moderator.blade.php
  resources/views/layouts/content-moderator.blade.php
  resources/views/moderator/overview.blade.php
Labels: enhancement, UI/UX

#140 Feature/favicon webpage title
  .env.example
  public/favicon.ico
Labels: enhancement, UI/UX

#119 Feature - Allow content moderator to override the difficulty level
  app/Http/Livewire/OverrideDifficulty.php
  resources/views/livewire/override-difficulty.blade.php
  resources/views/moderator/schedule/presentation-schedule.blade.php
Labels: enhancement, High Priority

#141 Ux rework/dashboard colour
  app/View/Components/ContentModeratorBlock.php
  app/View/Components/SidebarLinkContentMod.php
  resources/views/components/content-moderator-block.blade.php
  resources/views/components/sidebar-link-content-mod.blade.php
  resources/views/layouts/content-moderator.blade.php
  resources/views/moderator/overview.blade.php
  tailwind.config.js
Labels: enhancement, UI/UX

#98 Feature/notifications and emails
  app/Console/Kernel.php
  app/Http/Controllers/ContentModeratorController.php
  app/Http/Livewire/EmailNotificationPreference.php
  app/Http/Livewire/NotificationsList.php
  app/Http/Livewire/ShowNotification.php
  app/Mail/BoothApprovedMailable.php
  app/Mail/BoothDisapprovedMailable.php
  app/Mail/GenericNewUpdatesMailable.php
  app/Mail/PresentationApprovedMailable.php
  app/Mail/PresentationDisapprovedMailable.php
  app/Mail/SponsorshipApprovedMailable.php
  app/Mail/SponsorshipDisapprovedMailable.php
  app/Mail/TeamApprovedMailable.php
  app/Mail/TeamDisapprovedMailable.php
  app/Models/Booth.php
  app/Models/Notification.php
  app/Models/Presentation.php
  app/Models/Team.php
  app/Models/User.php
  app/Notifications/NotifyBoothApproved.php
  app/Notifications/NotifyBoothDisapproved.php
  app/Notifications/NotifyPresentationApproved.php
  app/Notifications/NotifyPresentationDisapproved.php
  app/Notifications/NotifySponsorshipApproved.php
  app/Notifications/NotifySponsorshipDisapproved.php
  app/Notifications/NotifyTeamApproved.php
  app/Notifications/NotifyTeamDisapproved.php
  app/Observers/BoothObserver.php
  app/Observers/SpeakerObserver.php
  app/Observers/TeamObserver.php
  app/Providers/EventServiceProvider.php
  database/migrations/2023_08_25_232339_create_notifications_table.php
  database/migrations/2023_08_26_180925_update_user_with_receive_email_preferences.php
  package-lock.json
  resources/views/emails/booth-approved.blade.php
  resources/views/emails/booth-disapproved.blade.php
  resources/views/emails/custom-team-invite.blade.php
  resources/views/emails/generic-new-updates.blade.php
  resources/views/emails/invite-company-rep.blade.php
  resources/views/emails/presentation-approved.blade.php
  resources/views/emails/presentation-disapproved.blade.php
  resources/views/emails/sponsorship-approved.blade.php
  resources/views/emails/sponsorship-disapproved.blade.php
  resources/views/emails/team-approved.blade.php
  resources/views/livewire/email-notification-preference.blade.php
  resources/views/livewire/notifications-list.blade.php
  resources/views/livewire/show-notification.blade.php
  resources/views/moderator/details/booth.blade.php
  resources/views/moderator/details/presentation.blade.php
  resources/views/moderator/details/sponsorship.blade.php
  resources/views/moderator/details/team.blade.php
  resources/views/myhub/announcement.blade.php
  resources/views/profile/show.blade.php
  routes/web.php
Labels: enhancement, High Priority

#158 Rework - Speakers page
  app/Http/Controllers/SpeakerController.php
  resources/views/companies.blade.php
  resources/views/speakers/index.blade.php
Labels: High Priority

#107 Feature - Final programme release
  app/Events/FinalProgrammeReleased.php
  app/Http/Controllers/InvitationController.php
  app/Http/Controllers/ScheduleController.php
  app/Http/Controllers/SpeakerController.php
  app/Http/Livewire/ReleaseFinalProgramme.php
  app/Listeners/HandleFinalProgrammeReleased.php
  app/Models/GlobalEvent.php
  app/Policies/PresentationPolicy.php
  app/Providers/EventServiceProvider.php
  database/migrations/2023_08_28_134602_create_global_events_table.php
  database/seeders/DatabaseSeeder.php
  resources/views/components/schedule-block.blade.php
  resources/views/livewire/auth-navigation-menu.blade.php
  resources/views/livewire/guest-navigation-menu.blade.php
  resources/views/livewire/release-final-programme.blade.php
  resources/views/moderator/schedule/index.blade.php
  resources/views/presentations/index.blade.php
  resources/views/presentations/show.blade.php
  resources/views/teams/team-member-manager.blade.php
  routes/web.php
Labels: enhancement, urgentissimo

#160 Fix - Bug when requesting presentation as independent speaker
  app/Http/Controllers/SpeakerController.php
Labels: bugfix

#167 Ux/upload presentation
  app/View/Components/PresentationDetails.php
  resources/views/components/presentation-details.blade.php
  resources/views/speakers/presentation/show.blade.php
Labels: UI/UX

#163 Update composer
  composer.lock
  package-lock.json
Labels: High Priority, dependencies

#164 Update npm packages for production
  package-lock.json
Labels: High Priority, dependencies

#149 Rework - gold sponsor flow
  app/Http/Controllers/HubController.php
  app/Http/Controllers/InvitationController.php
  app/Http/Controllers/SpeakerController.php
  app/Http/Responses/LoginResponse.php
  app/Models/SponsorTier.php
  app/Models/Team.php
  app/Policies/PresentationPolicy.php
  app/Providers/RouteServiceProvider.php
  app/View/Components/CompanyDashboardSection.php
  app/View/Components/CompanyRepBlock.php
  app/View/Components/GoldSponsorSpeakerBlock.php
  app/View/Components/SidebarLink.php
  resources/views/auth/register.blade.php
  resources/views/components/company-dashboard-section.blade.php
  resources/views/components/company-rep-block.blade.php
  resources/views/components/gold-sponsor-speaker-block.blade.php
  resources/views/components/schedule-block.blade.php
  resources/views/components/sidebar-link.blade.php
  resources/views/layouts/myhub.blade.php
  resources/views/layouts/old-myhub.blade.php
  resources/views/livewire/booth-request.blade.php
  resources/views/livewire/manage-company-logo.blade.php
  resources/views/livewire/notifications-list.blade.php
  resources/views/livewire/show-notification.blade.php
  resources/views/livewire/sponsorship-request.blade.php
  resources/views/moderator/overview.blade.php
  resources/views/myhub/home.blade.php
  resources/views/profile/delete-user-form.blade.php
  resources/views/profile/show.blade.php
  resources/views/speakers/presentation-request.blade.php
  resources/views/teams/delete-team-form.blade.php
  resources/views/teams/requests.blade.php
  resources/views/teams/show.blade.php
  resources/views/teams/team-member-manager.blade.php
  resources/views/teams/update-team-name-form.blade.php
  routes/web.php
Labels: enhancement, High Priority

#186 Refactor presentation policy logic
  app/Models/Team.php
  app/Policies/PresentationPolicy.php
Labels: enhancement

#124 Feature - show sponsors on main page
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/TeamsController.php
  app/Models/SponsorTier.php
  database/factories/TeamFactory.php
  database/seeders/DatabaseSeeder.php
  resources/views/welcome.blade.php
  routes/web.php
  tests/Feature/ExampleTest.php
  tests/Feature/RoomBasicFeaturesTest.php
Labels: enhancement, High Priority, UI/UX

#205 Date on the main page
  resources/views/components/countdown.blade.php
  resources/views/welcome.blade.php
Labels: bugfix, UI/UX

#190 Hotfix - front page responsiveness
  resources/views/companies.blade.php
  resources/views/faq.blade.php
  resources/views/livewire/guest-navigation-menu.blade.php
  resources/views/speakers/index.blade.php
Labels: bugfix, UI/UX

#215 Hotfix - Company logo update permissions
  app/Policies/TeamPolicy.php
  resources/views/teams/show.blade.php
Labels: bugfix

#218 Bugfix - Mobile authenticated main menu
  resources/views/livewire/auth-navigation-menu.blade.php
Labels: bugfix

#133 Ux rework/content management dashboard
  app/Models/User.php
  app/View/Components/ContentModBoothRequestDetails.php
  app/View/Components/ContentModCompanyRequestDetails.php
  app/View/Components/ContentModPresentationRequestDetails.php
  app/View/Components/ContentModSponsorRequestDetails.php
  package-lock.json
  public/img/logo-small-crew.png
  public/img/logo-small-participant.png
  public/img/logo-small-partner.png
  resources/views/components/content-mod-booth-request-details.blade.php
  resources/views/components/content-mod-company-request-details.blade.php
  resources/views/components/content-mod-presentation-request-details.blade.php
  resources/views/components/content-mod-sponsor-request-details.blade.php
  resources/views/components/sidebar-link.blade.php
  resources/views/layouts/hub.blade.php
  resources/views/moderator/details/booth.blade.php
  resources/views/moderator/details/presentation.blade.php
  resources/views/moderator/details/sponsorship.blade.php
  resources/views/moderator/details/team.blade.php
  resources/views/moderator/requests/booths.blade.php
  resources/views/moderator/requests/presentations.blade.php
  resources/views/moderator/requests/sponsorships.blade.php
  resources/views/moderator/requests/teams.blade.php
Labels: enhancement, bugfix, ui/ux

#238 Fix - Sponsor card
  resources/views/welcome.blade.php
Labels: high priority, bugfix, ui/ux

#213 Feature - HZ team
  app/Http/Controllers/InvitationController.php
  app/Http/Controllers/PresentationController.php
  app/Models/Team.php
  app/Models/User.php
  app/Policies/PresentationPolicy.php
  app/View/Components/HzTeamBlock.php
  resources/views/components/company-dashboard-section.blade.php
  resources/views/components/hz-team-block.blade.php
Labels: enhancement, high priority

#240 Fix - order of companies on company page and landing page
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/TeamsController.php
Labels: high priority, bugfix, ui/ux

#241 Fix - requesting presentation form issue
  resources/views/speakers/presentation/create.blade.php
Labels: high priority, bugfix

#239 Rework - My presentation
  app/Http/Controllers/PresentationController.php
  app/Http/Livewire/EditPresentationModal.php
  app/Http/Livewire/UploadPresentation.php
  app/Models/Presentation.php
  app/Policies/PresentationPolicy.php
  database/migrations/2023_09_22_162821_update_presentations_table_with_original_file_name.php
  resources/views/livewire/edit-presentation-modal.blade.php
  resources/views/livewire/upload-presentation.blade.php
  resources/views/speakers/presentation/edit.blade.php
  resources/views/speakers/presentation/show.blade.php
  routes/web.php
Labels: enhancement, high priority

#246 Update npm packages
  package-lock.json
Labels: medium priority, dependencies, production

#248 Update composer packages
  composer.lock
Labels: medium priority, dependencies, production

#249 UX/UI - HZ team colours and text
  app/Http/Controllers/PresentationController.php
  resources/views/components/hz-team-block.blade.php
  resources/views/speakers/presentation/create.blade.php
Labels: bugfix, ui/ux

#253 Fix - Automatically confirm email when company rep is invited and signs in
  app/Http/Controllers/InvitationController.php
Labels: high priority, bugfix

#255 Fix - Create artisan function that confirms emails of all already registered users
  app/Console/Commands/ConfirmAllEmails.php
Labels: bugfix

#245 Fix - Add users to HZ team
  app/Console/Commands/AddToHz.php
Labels: bugfix
