Repository HZ-HBO-ICT/it-conference, pull requests merged in 2024-05, with the labels that each got.

#408 Update README.md
  README.md
Labels: documentation, low priority

#404 Bugfix - Profile picture filtering
  app/Livewire/Company/ManageLogo.php
  resources/views/livewire/company/manage-logo.blade.php
  resources/views/livewire/presentation/upload-presentation.blade.php
  resources/views/profile/update-profile-information-form.blade.php
Labels: bugfix, frontend

#411 Feature/sync permissions command
  app/Console/Commands/SyncPermissions.php
  app/Console/Commands/UpsertMasterData.php
  app/Http/Controllers/Crew/BoothController.php
  app/Http/Controllers/Crew/CompanyController.php
  app/Http/Controllers/Crew/PresentationController.php
  app/Http/Controllers/Crew/RoomController.php
  app/Livewire/Company/DeleteCompany.php
  app/Livewire/Company/EditCompanyModal.php
  app/Models/Company.php
  app/Models/Presentation.php
  app/Models/User.php
  app/Policies/BoothPolicy.php
  app/Policies/CompanyPolicy.php
  app/Policies/PresentationPolicy.php
  app/Policies/RoomPolicy.php
  app/Policies/SponsorshipPolicy.php
  app/Policies/TeamPolicy.php
  database/factories/UserFactory.php
  database/seeders/CompanySeeder.php
  database/seeders/DatabaseSeeder.php
  database/seeders/PermissionSeeder.php
  database/seeders/UserSeeder.php
  package-lock.json
  resources/views/components/dashboards/crew.blade.php
  resources/views/crew/booths/show.blade.php
  resources/views/crew/companies/show.blade.php
  resources/views/crew/presentations/create.blade.php
  resources/views/crew/presentations/show.blade.php
  resources/views/crew/sponsorships/index.blade.php
  resources/views/crew/sponsorships/show.blade.php
  resources/views/livewire/company/add-member.blade.php
  resources/views/livewire/company/details-form.blade.php
  resources/views/livewire/company/manage-logo.blade.php
  resources/views/livewire/company/member-manager.blade.php
  resources/views/livewire/presentation/upload-presentation.blade.php
  resources/views/myhub/company/details.blade.php
  resources/views/myhub/home.blade.php
  storage/app/.gitignore
  storage/app/config/permissions.yml
  tests/Feature/BoothControllerTest.php
  tests/Feature/CompanyControllerTest.php
  tests/Feature/PresentationControllerTest.php
  tests/Feature/RegistrationTest.php
  tests/Feature/RoomControllerTest.php
  tests/Feature/SponsorshipControllerTest.php
  tests/Feature/SyncPermissionsTest.php
  tests/Unit/CreateNewUserTest.php
  tests/Unit/PresentationTest.php
  tests/Unit/UserTest.php
Labels: feature, backend
