Repository HZ-HBO-ICT/it-conference, pull requests merged in 2024-04, with the labels that each got.

#384 Feature - Database implementation
  app/Console/Commands/UpsertMasterData.php
  app/Models/Booth.php
  app/Models/Company.php
  app/Models/Difficulty.php
  app/Models/FrequentQuestion.php
  app/Models/Invitation.php
  app/Models/Presentation.php
  app/Models/Room.php
  app/Models/Sponsorship.php
  app/Models/Timeslot.php
  app/Models/User.php
  app/Models/UserPresentation.php
  composer.json
  composer.lock
  config/permission.php
  database/factories/BoothFactory.php
  database/factories/CompanyFactory.php
  database/factories/PresentationFactory.php
  database/factories/RoomFactory.php
  database/factories/TimeslotFactory.php
  database/factories/UserFactory.php
  database/migrations/0001_01_01_000000_create_users_table.php
  database/migrations/2024_03_22_133611_create_permission_tables.php
  database/migrations/2024_03_25_160546_create_sponsorships_table.php
  database/migrations/2024_03_25_161038_create_companies_table.php
  database/migrations/2024_03_25_162647_create_booths_table.php
  database/migrations/2024_03_26_082055_create_invitations_table.php
  database/migrations/2024_03_26_092123_add_foreign_key_referencing_companies_in_users_table.php
  database/migrations/2024_03_26_093819_create_difficulties_table.php
  database/migrations/2024_03_26_093925_create_rooms_table.php
  database/migrations/2024_03_26_094033_create_timeslots_table.php
  database/migrations/2024_03_26_094332_create_presentations_table.php
  database/migrations/2024_03_27_092645_create_user_presentations_table.php
  database/migrations/2024_03_27_101334_create_notifications_table.php
  database/migrations/2024_03_27_102551_create_frequent_questions_table.php
  database/seeders/CompanySeeder.php
  database/seeders/DatabaseSeeder.php
  database/seeders/UserSeeder.php
  tests/Feature/EmailVerificationTest.php
  tests/Feature/PasswordConfirmationTest.php
  tests/Unit/PresentationTest.php
  tests/Unit/UserTest.php
Labels: high priority, backend, rework

#388 Feature - Basic Registration routes
  app/Actions/Fortify/CreateNewUser.php
  app/Actions/Fortify/PasswordValidationRules.php
  app/Http/Controllers/HubController.php
  app/Models/Company.php
  app/Models/User.php
  app/Policies/CompanyPolicy.php
  app/Policies/PresentationPolicy.php
  app/Providers/AppServiceProvider.php
  config/fortify.php
  resources/views/auth/register.blade.php
  resources/views/components/company-dashboard-section.blade.php
  resources/views/components/sidemenus/company.blade.php
  resources/views/layouts/hub.blade.php
  resources/views/myhub/announcement.blade.php
  resources/views/myhub/home.blade.php
  routes/web.php
  tests/Feature/PasswordResetTest.php
  tests/Feature/RegistrationTest.php
  tests/Feature/UpdatePasswordTest.php
  tests/Unit/CreateNewUserTest.php
Labels: feature, backend

#394 Bugfix - Dark mode flicker
  resources/js/app.js
  resources/views/layouts/app.blade.php
  resources/views/livewire/auth-navigation-menu.blade.php
  resources/views/livewire/guest-navigation-menu.blade.php
Labels: bugfix, frontend

#400 Frontend rework/#380 contact page
  .env.example
  package-lock.json
  package.json
  resources/css/app.css
  resources/js/app.js
  resources/js/googleMaps.js
  resources/js/mapBox.js
  resources/views/components/map.blade.php
  resources/views/contact.blade.php
  resources/views/layouts/app.blade.php
Labels: feature, frontend, rework

#399 Rework - Requesting presentations
  app/Http/Controllers/PresentationController.php
  app/Livewire/Forms/PresentationForm.php
  app/Livewire/Presentation/DeletePresentationModal.php
  app/Livewire/Presentation/EditPresentationModal.php
  app/Livewire/Presentation/UploadPresentation.php
  app/Models/Company.php
  app/Models/Presentation.php
  app/Policies/PresentationPolicy.php
  database/migrations/2024_03_26_094332_create_presentations_table.php
  resources/views/components/livewire-modal.blade.php
  resources/views/components/sidemenus/company.blade.php
  resources/views/layouts/guest.blade.php
  resources/views/livewire/presentation/delete-presentation-modal.blade.php
  resources/views/livewire/presentation/edit-presentation-modal.blade.php
  resources/views/livewire/presentation/upload-presentation.blade.php
  resources/views/presentations/create.blade.php
  resources/views/presentations/delete-presentation-form.blade.php
  resources/views/presentations/edit-presentation-modal.blade.php
  resources/views/presentations/show.blade.php
  routes/web.php
  tailwind.config.js
Labels: feature, backend

#405 Bugfix - Missing approval status on presentations table
  database/migrations/2024_03_26_094332_create_presentations_table.php
Labels: bugfix, backend
