Repository HZ-HBO-ICT/it-conference, pull requests merged in 2024-10, with the labels that each got.

#548 Feature - Add confirmation modals for approving rejecting
  app/Http/Controllers/Crew/BoothController.php
  app/Http/Controllers/Crew/CompanyController.php
  app/Http/Controllers/Crew/PresentationController.php
  app/Http/Controllers/Crew/SponsorshipController.php
  app/Livewire/ConfirmationModal.php
  resources/views/components/livewire-modal.blade.php
  resources/views/crew/booths/show.blade.php
  resources/views/crew/companies/show.blade.php
  resources/views/crew/presentations/show.blade.php
  resources/views/crew/sponsorships/show.blade.php
  resources/views/livewire/confirmation-modal.blade.php
  routes/web.php
  tests/Feature/BoothControllerTest.php
  tests/Feature/CompanyControllerTest.php
  tests/Feature/PresentationControllerTest.php
  tests/Feature/SponsorshipControllerTest.php
Labels: frontend, crew

#553 Feature - Add participant to company
  app/Actions/Users/AddParticipantToCompanyHandler.php
  app/Console/Commands/AddParticipantToCompany.php
  app/Livewire/Company/AddParticipant.php
  app/Policies/CompanyPolicy.php
  resources/views/crew/companies/show.blade.php
  resources/views/layouts/app.blade.php
  resources/views/livewire/company/add-participant.blade.php
  storage/app/config/permissions.yml
Labels: high priority, bugfix, company

#559 Feature - Better design crew index pages
  resources/views/crew/booths/index.blade.php
  resources/views/crew/companies/index.blade.php
  resources/views/crew/companies/show.blade.php
  resources/views/crew/editions/index.blade.php
  resources/views/crew/faqs/index.blade.php
  resources/views/crew/presentations/index.blade.php
  resources/views/crew/rooms/index.blade.php
  resources/views/crew/sponsorships/index.blade.php
Labels: frontend, crew

#567 Bugfix - Doubled countdown
  resources/views/components/countdown.blade.php
Labels: bugfix

#561 Bugfix - Registering buttons bug
  resources/views/welcome.blade.php
Labels: bugfix, frontend

#560 Bugfix - Sponsors on welcome
  resources/views/welcome.blade.php
Labels: bugfix, frontend

#562 Feature - Notify users on presentation/company update
  app/Http/Controllers/Crew/CompanyController.php
  app/Http/Controllers/Crew/PresentationController.php
  app/Jobs/NotifyCompanyRoles.php
  app/Jobs/NotifyPresentationRoles.php
  app/Livewire/Company/EditCompanyModal.php
  app/Livewire/Presentation/EditPresentationModal.php
  app/Mail/CompanyDeletedMailable.php
  app/Mail/CompanyUpdatedMailable.php
  app/Mail/PresentationDeletedMailable.php
  app/Mail/PresentationUpdatedMailable.php
  app/Models/Company.php
  app/Models/Presentation.php
  resources/views/emails/company-deleted.blade.php
  resources/views/emails/company-updated.blade.php
  resources/views/emails/presentation-deleted.blade.php
  resources/views/emails/presentation-updated.blade.php
Labels: feature, high priority

#564 Feature - Feedback system
  app/Http/Controllers/Crew/FeedbackController.php
  app/Http/Controllers/Hub/ParticipantController.php
  app/Livewire/Crew/AddTeam.php
  app/Mail/FeedbackReceivedMailable.php
  app/Models/Feedback.php
  app/Models/User.php
  app/Observers/FeedbackObserver.php
  app/Policies/FeedbackPolicy.php
  database/migrations/2024_10_16_141617_add_tag_to_users_for_crew.php
  database/migrations/2024_10_19_160643_create_feedback_table.php
  resources/views/components/dashboards/blocks/participant-notification.blade.php
  resources/views/components/dashboards/company.blade.php
  resources/views/components/sidemenus/content-moderator.blade.php
  resources/views/crew/crew/index.blade.php
  resources/views/crew/feedback/index.blade.php
  resources/views/crew/feedback/show.blade.php
  resources/views/emails/feedback-received.blade.php
  resources/views/layouts/hub.blade.php
  resources/views/livewire/crew/add-team.blade.php
  resources/views/myhub/feedback.blade.php
  resources/views/myhub/home.blade.php
  routes/web.php
  storage/app/config/permissions.yml
Labels: feature
