Repository HZ-HBO-ICT/it-conference, pull requests merged in 2024-09, with the labels that each got.

#526 Rework - Companies and Speakers front facing pages
  app/Http/Controllers/CompanyController.php
  app/Http/Controllers/ProgrammeController.php
  app/Livewire/Company/ManageLogo.php
  app/Models/Company.php
  app/Models/Edition.php
  app/View/Components/Company/CompanyLogosManager.php
  config/routesWithFooter.php
  database/factories/CompanyFactory.php
  database/migrations/2024_03_25_161038_create_companies_table.php
  resources/views/components/company/company-logos-manager.blade.php
  resources/views/crew/companies/show.blade.php
  resources/views/faq.blade.php
  resources/views/layouts/app.blade.php
  resources/views/livewire/company/manage-logo.blade.php
  resources/views/livewire/registration/select-country-code.blade.php
  resources/views/myhub/company/details.blade.php
  resources/views/programme/index.blade.php
  resources/views/programme/show.blade.php
  resources/views/speakers/index.blade.php
  resources/views/teams/public/index.blade.php
  resources/views/teams/public/show.blade.php
  routes/web.php
Labels: frontend, rework

#535 Dependencies
  composer.lock
  package-lock.json
Labels: dependencies

#533 Feature - Role management
  app/Actions/Permissions/ReadPermissionConfig.php
  app/Console/Commands/SyncPermissions.php
  app/Http/Controllers/Crew/CrewController.php
  app/Livewire/Crew/AssignRoleToUser.php
  app/Livewire/Crew/RevokeRoleOfUser.php
  app/Livewire/Crew/RolePermissionsInfo.php
  app/Providers/AppServiceProvider.php
  resources/views/components/sidemenus/content-moderator.blade.php
  resources/views/crew/crew/index.blade.php
  resources/views/layouts/hub.blade.php
  resources/views/livewire/crew/assign-role-to-user.blade.php
  resources/views/livewire/crew/revoke-role-of-user.blade.php
  resources/views/livewire/crew/role-permissions-info.blade.php
  routes/web.php
  storage/app/config/permissions.yml
  tests/Feature/SyncPermissionsTest.php
Labels: high priority, crew

#540 Feature - Logging activity
  app/Actions/Log/ApprovalHandler.php
  app/Http/Controllers/Crew/SponsorshipController.php
  app/Models/Booth.php
  app/Models/Company.php
  app/Models/Presentation.php
  app/Models/User.php
  app/View/Components/Dashboards/Blocks/Log.php
  composer.json
  composer.lock
  database/migrations/2024_09_11_094258_create_activity_log_table.php
  database/migrations/2024_09_11_094259_add_event_column_to_activity_log_table.php
  database/migrations/2024_09_11_094300_add_batch_uuid_column_to_activity_log_table.php
  database/seeders/DatabaseSeeder.php
  resources/views/components/dashboards/blocks/log.blade.php
  resources/views/components/dashboards/crew.blade.php
  tests/Feature/BoothControllerTest.php
  tests/Feature/CompanyControllerTest.php
  tests/Feature/PresentationControllerTest.php
  tests/Feature/RoomControllerTest.php
  tests/Feature/SponsorshipControllerTest.php
  tests/Unit/CreateNewUserTest.php
  tests/Unit/PresentationTest.php
  tests/Unit/UserTest.php
Labels: crew

#544 Bugfix - High priority issuses
  README.md
  app/Http/Controllers/Crew/BoothController.php
  app/Http/Controllers/Crew/CrewController.php
  app/Http/Controllers/Crew/RoomController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/ProgrammeController.php
  app/Http/Controllers/SpeakerController.php
  app/Livewire/Booth/CreateBooth.php
  app/Livewire/Company/AddMember.php
  app/Mail/BoothDisapprovedMailable.php
  app/Mail/PresentationDisapprovedMailable.php
  app/Mail/SponsorshipDisapprovedMailable.php
  app/Models/Presentation.php
  app/Policies/RoomPolicy.php
  database/factories/CompanyFactory.php
  public/js/registration-validation.js
  resources/views/crew/booths/create.blade.php
  resources/views/crew/companies/create.blade.php
  resources/views/crew/companies/show.blade.php
  resources/views/crew/rooms/show.blade.php
  resources/views/livewire/booth/create-booth.blade.php
  resources/views/livewire/registration/select-country-code.blade.php
  resources/views/livewire/schedule/grid-parent-component.blade.php
  resources/views/programme/show.blade.php
  resources/views/teams/public/index.blade.php
  resources/views/teams/public/show.blade.php
  resources/views/welcome.blade.php
  routes/web.php
  tailwind.config.js
  tests/Feature/BoothControllerTest.php
Labels: bugfix

#549 Development
  README.md
  app/Http/Controllers/Crew/BoothController.php
  app/Http/Controllers/Crew/CrewController.php
  app/Http/Controllers/Crew/RoomController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/ProgrammeController.php
  app/Http/Controllers/SpeakerController.php
  app/Livewire/Booth/CreateBooth.php
  app/Livewire/Company/AddMember.php
  app/Mail/BoothDisapprovedMailable.php
  app/Mail/PresentationDisapprovedMailable.php
  app/Mail/SponsorshipDisapprovedMailable.php
  app/Models/Presentation.php
  app/Policies/RoomPolicy.php
  database/factories/CompanyFactory.php
  public/js/registration-validation.js
  resources/views/crew/booths/create.blade.php
  resources/views/crew/companies/create.blade.php
  resources/views/crew/companies/show.blade.php
  resources/views/crew/rooms/show.blade.php
  resources/views/livewire/booth/create-booth.blade.php
  resources/views/livewire/registration/select-country-code.blade.php
  resources/views/livewire/schedule/grid-parent-component.blade.php
  resources/views/programme/show.blade.php
  resources/views/teams/public/index.blade.php
  resources/views/teams/public/show.blade.php
  resources/views/welcome.blade.php
  routes/web.php
  tailwind.config.js
  tests/Feature/BoothControllerTest.php
Labels: production
