Repository HZ-HBO-ICT/it-conference, pull requests merged in 2024-07, with the labels that each got.

#443 Fix countdown not showing when navigating between pages (#413)
  resources/views/components/countdown.blade.php
Labels: bugfix

#439 Bugfix - Issue #423 - Phone number validation consistency
  app/Actions/Fortify/CreateNewUser.php
  app/Http/Controllers/Crew/CompanyController.php
  app/Livewire/Registration/CompanyBasicForm.php
  app/Livewire/Registration/ParentComponent.php
  database/migrations/2024_03_25_161038_create_companies_table.php
  resources/views/crew/companies/create.blade.php
  resources/views/livewire/registration/company-basic-form.blade.php
Labels: bugfix

#440 Rework - 431 company roles and features
  app/Console/Commands/ApproveLastCreatedCompany.php
  app/Http/Controllers/Hub/CompanyController.php
  app/Http/Controllers/Hub/HubController.php
  app/Http/Controllers/InvitationController.php
  app/Http/Controllers/PresentationController.php
  app/Livewire/Booth/JoinBoothOwnerModal.php
  app/Livewire/Company/AddMember.php
  app/Livewire/Company/BoothRequest.php
  app/Livewire/Presentation/JoinAsSpeakerModal.php
  app/Models/Presentation.php
  app/Models/User.php
  app/Policies/CompanyPolicy.php
  app/Policies/PresentationPolicy.php
  app/View/Components/Dashboards/Blocks/CompanyRoleDecider.php
  resources/views/auth/registration-via-invitation.blade.php
  resources/views/components/dashboards/blocks/company-role-decider.blade.php
  resources/views/components/dashboards/company.blade.php
  resources/views/components/gold-sponsor-speaker-block.blade.php
  resources/views/components/hz-team-block.blade.php
  resources/views/components/sidemenus/company.blade.php
  resources/views/layouts/hub.blade.php
  resources/views/livewire/booth/join-booth-owner-modal.blade.php
  resources/views/livewire/company/add-member.blade.php
  resources/views/livewire/presentation/join-as-speaker-modal.blade.php
  resources/views/livewire/presentation/upload-presentation.blade.php
  resources/views/myhub/company/requests.blade.php
  resources/views/presentations/create.blade.php
  resources/views/presentations/show.blade.php
  routes/web.php
  storage/app/config/permissions.yml
Labels: high priority, bugfix, backend, company

#442 Feature - Edition management (without scheduler)
  app/Console/Commands/UpsertMasterData.php
  app/Http/Controllers/Crew/EditionController.php
  app/Http/Controllers/Crew/EditionEventController.php
  app/Http/Controllers/HomeController.php
  app/Listeners/HandleFinalProgrammeReleased.php
  app/Livewire/Edition/ActivateEditionModal.php
  app/Livewire/Edition/DeleteEditionModal.php
  app/Livewire/Edition/EditEditionModal.php
  app/Livewire/EditionEvent/EditEditionEventModal.php
  app/Livewire/Forms/EditionEventForm.php
  app/Livewire/Forms/EditionForm.php
  app/Models/Edition.php
  app/Models/EditionEvent.php
  app/Models/Event.php
  app/Models/EventInstance.php
  app/Policies/EditionPolicy.php
  app/Policies/PresentationPolicy.php
  bootstrap/app.php
  database/migrations/2023_09_13_130057_create_editions_table.php
  database/migrations/2024_04_25_125646_create_events_table.php
  database/migrations/2024_04_25_130428_create_edition_events_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/EditionSeeder.php
  resources/views/components/countdown.blade.php
  resources/views/components/sidebar-link-content-mod.blade.php
  resources/views/components/sidemenus/content-moderator.blade.php
  resources/views/livewire/auth-navigation-menu.blade.php
  resources/views/livewire/edition-event/edit-edition-event-modal.blade.php
  resources/views/livewire/edition/activate-edition-modal.blade.php
  resources/views/livewire/edition/delete-edition-modal.blade.php
  resources/views/livewire/edition/edit-edition-modal.blade.php
  resources/views/livewire/guest-navigation-menu.blade.php
  resources/views/livewire/presentation/upload-presentation.blade.php
  resources/views/moderator/editions/create.blade.php
  resources/views/moderator/editions/index.blade.php
  resources/views/moderator/events/index.blade.php
  resources/views/moderator/schedule/presentations/show.blade.php
  resources/views/presentations/show.blade.php
  resources/views/welcome.blade.php
  routes/web.php
  storage/app/config/permissions.yml
Labels: feature, high priority, frontend, backend, crew

#445 Feature - Scheduling system feedback implementation
  app/Actions/Schedule/PresentationConflictChecker.php
  app/Http/Controllers/Crew/ScheduleController.php
  app/Livewire/Forms/DefaultPresentationForm.php
  app/Livewire/Schedule/AddDefaultPresentation.php
  app/Livewire/Schedule/Cell.php
  app/Livewire/Schedule/ConfirmResetScheduleModal.php
  app/Livewire/Schedule/EditDefaultPresentationModal.php
  app/Livewire/Schedule/GridParentComponent.php
  app/Livewire/Schedule/Presentation.php
  app/Models/DefaultPresentation.php
  app/Models/Presentation.php
  app/Models/Sponsorship.php
  app/Models/Timeslot.php
  app/View/Components/Schedule/SetDefaultPresentations.php
  database/migrations/2024_06_26_132929_create_default_presentations_table.php
  database/seeders/DatabaseSeeder.php
  package-lock.json
  resources/views/components/schedule/set-default-presentations.blade.php
  resources/views/crew/schedule/index.blade.php
  resources/views/livewire/schedule/add-default-presentation.blade.php
  resources/views/livewire/schedule/cell.blade.php
  resources/views/livewire/schedule/confirm-reset-schedule-modal.blade.php
  resources/views/livewire/schedule/edit-default-presentation-modal.blade.php
  resources/views/livewire/schedule/grid-parent-component.blade.php
  resources/views/livewire/schedule/presentation.blade.php
  routes/web.php
  tailwind.config.js
Labels: feature, frontend, crew

#446 Rework - #433 Registration fields
  app/Actions/Fortify/CreateNewUser.php
  app/Livewire/Registration/CompanyInternshipsForm.php
  app/Livewire/Registration/CompanyMotivationForm.php
  app/Livewire/Registration/ParentComponent.php
  app/Models/Company.php
  app/Models/InternshipAttribute.php
  database/factories/CompanyFactory.php
  database/migrations/2024_03_25_161038_create_companies_table.php
  database/migrations/2024_07_01_115148_create_internship_attributes_table.php
  resources/views/crew/companies/show.blade.php
  resources/views/livewire/registration/company-internships-form.blade.php
  resources/views/livewire/registration/company-motivation-form.blade.php
  resources/views/livewire/registration/parent-component.blade.php
  tests/Unit/CreateNewUserTest.php
Labels: feature, frontend

#452 Feature - Programme release prerequisites
  app/Http/Controllers/Crew/ScheduleController.php
  app/Livewire/Schedule/AddDefaultPresentation.php
  app/Livewire/Schedule/Cell.php
  app/Livewire/Schedule/EditDefaultPresentationModal.php
  app/Livewire/Schedule/GridParentComponent.php
  app/Livewire/Schedule/Presentation.php
  app/Livewire/Schedule/PresentationModal.php
  app/Livewire/Schedule/PublishProgrammeButton.php
  app/Livewire/Schedule/PublishProgrammeModal.php
  app/Models/Edition.php
  app/Models/Presentation.php
  app/Providers/AppServiceProvider.php
  database/factories/CompanyFactory.php
  database/factories/PresentationFactory.php
  database/factories/RoomFactory.php
  database/seeders/CompanySeeder.php
  database/seeders/DatabaseSeeder.php
  resources/views/crew/schedule/index.blade.php
  resources/views/livewire/auth-navigation-menu.blade.php
  resources/views/livewire/guest-navigation-menu.blade.php
  resources/views/livewire/presentation/edit-presentation-modal.blade.php
  resources/views/livewire/schedule/cell.blade.php
  resources/views/livewire/schedule/confirm-reset-schedule-modal.blade.php
  resources/views/livewire/schedule/grid-parent-component.blade.php
  resources/views/livewire/schedule/presentation-modal.blade.php
  resources/views/livewire/schedule/publish-programme-button.blade.php
  resources/views/livewire/schedule/publish-programme-modal.blade.php
  routes/web.php
  tailwind.config.js
  tests/Feature/CompanyControllerTest.php
  tests/Feature/PresentationControllerTest.php
  tests/Feature/RoomControllerTest.php
Labels: frontend, backend, crew

#454 Bugfix - Scrollbar, Booth redirection and Sponsorships badge
  app/Http/Controllers/Crew/BoothController.php
  resources/views/components/sidemenus/content-moderator.blade.php
  resources/views/layouts/hub.blade.php
  tests/Feature/BoothControllerTest.php
Labels: bugfix

#453 Rework - Programme enrollment
  app/Http/Controllers/Hub/ParticipantController.php
  app/Http/Controllers/ProgrammeController.php
  app/Models/DefaultPresentation.php
  app/Models/Presentation.php
  app/Models/Room.php
  app/Models/User.php
  app/Policies/PresentationPolicy.php
  database/migrations/2024_04_25_130428_create_edition_events_table.php
  resources/views/components/schedule-block.blade.php
  resources/views/layouts/hub.blade.php
  resources/views/livewire/auth-navigation-menu.blade.php
  resources/views/myhub/programme.blade.php
  resources/views/programme/index.blade.php
  resources/views/programme/show.blade.php
  resources/views/welcome.blade.php
  routes/web.php
  tailwind.config.js
Labels: feature, high priority, frontend, backend, participant

#419 Rework/#418 content moderator dashboard redesign
  app/Console/Commands/AddSpeakerToPresentation.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/Hub/CompanyController.php
  app/Http/Controllers/ProgrammeController.php
  app/Livewire/NotificationsList.php
  app/Mail/PresentationApprovedMailable.php
  app/Models/User.php
  app/View/Components/ContentModBoothRequestDetails.php
  app/View/Components/ContentModCompanyRequestDetails.php
  app/View/Components/ContentModPresentationRequestDetails.php
  app/View/Components/ContentModSponsorRequestDetails.php
  app/View/Components/Dashboards/Blocks/Crew.php
  composer.lock
  database/migrations/2024_05_12_200203_create_stats_tables.php
  public/img/logo-small-apricot-peach.png
  resources/views/components/content moderator/content-mod-booth-request-details.blade.php
  resources/views/components/content moderator/content-mod-company-request-details.blade.php
  resources/views/components/content moderator/content-mod-presentation-request-details.blade.php
  resources/views/components/content moderator/content-mod-sponsor-request-details.blade.php
  resources/views/components/dashboards/blocks/crew.blade.php
  resources/views/components/dashboards/crew.blade.php
  resources/views/components/dropdown-link.blade.php
  resources/views/components/dropdown.blade.php
  resources/views/components/list-section-item.blade.php
  resources/views/components/schedule/set-default-presentations.blade.php
  resources/views/components/sidebar-link-content-mod.blade.php
  resources/views/components/sidebar-link.blade.php
  resources/views/components/sidemenus/content-moderator.blade.php
  resources/views/components/welcome.blade.php
  resources/views/crew/booths/index.blade.php
  resources/views/crew/companies/index.blade.php
  resources/views/crew/presentations/index.blade.php
  resources/views/crew/rooms/index.blade.php
  resources/views/crew/schedule/index.blade.php
  resources/views/crew/sponsorships/index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/hub.blade.php
  resources/views/livewire/auth-navigation-menu.blade.php
  resources/views/livewire/guest-navigation-menu.blade.php
  resources/views/moderator/details/booth.blade.php
  resources/views/moderator/details/presentation.blade.php
  resources/views/moderator/details/sponsorship.blade.php
  resources/views/moderator/details/team.blade.php
  resources/views/moderator/editions/create.blade.php
  resources/views/moderator/editions/index.blade.php
  resources/views/moderator/events/index.blade.php
  resources/views/myhub/home.blade.php
  resources/views/welcome.blade.php
  routes/web.php
  tailwind.config.js
Labels: high priority, bugfix, frontend, technical debt, rework, crew

#456 Rework - Automatic mailing
  app/Http/Controllers/Crew/BoothController.php
  app/Http/Controllers/Crew/CompanyController.php
  app/Http/Controllers/Crew/PresentationController.php
  app/Http/Controllers/Crew/ScheduleController.php
  app/Http/Controllers/Crew/SponsorshipController.php
  app/Listeners/HandleFinalProgrammeReleased.php
  app/Livewire/Company/AddMember.php
  app/Livewire/Schedule/PresentationModal.php
  app/Mail/BoothApprovedMailable.php
  app/Mail/BoothDisapprovedMailable.php
  app/Mail/CancelledPresentationMailable.php
  app/Mail/CompanyApprovedMailable.php
  app/Mail/CompanyDisapprovedMailable.php
  app/Mail/CompanyRepInvitation.php
  app/Mail/CustomCompanyInvitation.php
  app/Mail/FinalProgrammeReleasedMailable.php
  app/Mail/SponsorshipDisapprovedMailable.php
  app/Mail/UserInvitation.php
  app/Models/Company.php
  app/Notifications/NotifyPresentationApproved.php
  app/Notifications/NotifyTeamApproved.php
  app/Notifications/NotifyTeamDisapproved.php
  app/Policies/TeamPolicy.php
  database/seeders/CompanySeeder.php
  resources/views/emails/booth-approved.blade.php
  resources/views/emails/booth-disapproved.blade.php
  resources/views/emails/cancelled-presentation.blade.php
  resources/views/emails/company-approved.blade.php
  resources/views/emails/company-disapproved.blade.php
  resources/views/emails/custom-company-invite.blade.php
  resources/views/emails/custom-team-invite.blade.php
  resources/views/emails/final-programme-released.blade.php
  resources/views/emails/generic-new-updates.blade.php
  resources/views/emails/invite-company-rep.blade.php
  resources/views/emails/presentation-approved.blade.php
  resources/views/emails/presentation-disapproved.blade.php
  resources/views/emails/sponsorship-approved.blade.php
  resources/views/emails/sponsorship-disapproved.blade.php
  resources/views/emails/team-approved.blade.php
  resources/views/emails/team-disapproved.blade.php
  resources/views/emails/team-invitation.blade.php
  resources/views/emails/user-invite.blade.php
  tests/Feature/BoothControllerTest.php
  tests/Feature/CompanyControllerTest.php
  tests/Feature/SponsorshipControllerTest.php
Labels: high priority, backend

#457 Feature - Users page and emails
  app/Http/Controllers/Crew/UserController.php
  app/Http/Controllers/HomeController.php
  app/Livewire/Users/UserFilteringList.php
  app/Models/User.php
  app/Policies/UserPolicy.php
  database/factories/UserFactory.php
  resources/views/crew/users/index.blade.php
  resources/views/livewire/users/user-filtering-list.blade.php
  storage/app/config/permissions.yml
Labels: feature, frontend, crew

#460 Rework - Display sponsors on welcome page
  config/livewire.php
  database/factories/CompanyFactory.php
  resources/views/livewire/company/manage-logo.blade.php
  resources/views/welcome.blade.php
  tests/Feature/ExampleTest.php
Labels: frontend

#459 Changed colours to blue
  resources/views/components/schedule-block.blade.php
  resources/views/programme/index.blade.php
Labels: frontend, rework

#461 Add check for showing register buttons on homepage
  resources/views/welcome.blade.php
Labels: bugfix, frontend, backend

#462 Feature - Keynote speaker
  app/Http/Controllers/Crew/BoothController.php
  app/Http/Controllers/Crew/CompanyController.php
  app/Http/Controllers/Crew/PresentationController.php
  app/Http/Controllers/Crew/SponsorshipController.php
  app/Http/Controllers/SpeakerController.php
  app/Livewire/Edition/AddKeynoteModal.php
  app/Livewire/Forms/KeynoteForm.php
  app/Models/Edition.php
  database/migrations/2023_09_13_130057_create_editions_table.php
  resources/views/livewire/edition/add-keynote-modal.blade.php
  resources/views/moderator/editions/create.blade.php
  resources/views/moderator/editions/index.blade.php
  resources/views/moderator/events/index.blade.php
  resources/views/speakers/index.blade.php
Labels: feature, high priority, frontend, backend

#463 Bugfix - Registration routes
  app/Http/Controllers/RegistrationController.php
  routes/web.php
  tests/Feature/RegistrationTest.php
Labels: frontend

#513 Bugfix/welcome page
  resources/views/crew/sponsorships/index.blade.php
  resources/views/faq.blade.php
  resources/views/layouts/app.blade.php
  resources/views/welcome.blade.php
Labels: bugfix, frontend

#500 Rework - Schedule feedback implementation
  app/Actions/Schedule/ResetSchedule.php
  app/Http/Controllers/Crew/EditionController.php
  app/Http/Controllers/Crew/ScheduleController.php
  app/Livewire/Forms/DefaultPresentationForm.php
  app/Livewire/Schedule/DefaultPresentation.php
  app/Livewire/Schedule/PresentationModal.php
  app/Livewire/Schedule/PublishProgrammeButton.php
  app/View/Components/Schedule/ProgressBar.php
  resources/css/app.css
  resources/views/components/schedule/progress-bar.blade.php
  resources/views/components/schedule/set-default-presentations.blade.php
  resources/views/crew/schedule/index.blade.php
  resources/views/livewire/schedule/add-default-presentation.blade.php
  resources/views/livewire/schedule/default-presentation.blade.php
  resources/views/livewire/schedule/grid-parent-component.blade.php
  resources/views/livewire/schedule/publish-programme-button.blade.php
  tailwind.config.js
Labels: bugfix, frontend

#517 Bugfix - Speaker role in user filter
  app/Livewire/Users/UserFilteringList.php
  app/Models/User.php
  resources/views/livewire/users/user-filtering-list.blade.php
Labels: bugfix, frontend

#521 Update dependencies
  composer.lock
  package-lock.json
Labels: dependencies

#516 Rework - Registration UX
  app/Actions/Fortify/CreateNewUser.php
  app/Http/Controllers/Crew/CompanyController.php
  app/Livewire/Registration/CompanyBasicForm.php
  app/Livewire/Registration/CompanyLocationForm.php
  app/Livewire/Registration/CompanyMotivationForm.php
  app/Livewire/Registration/CompanyRepresentativeForm.php
  app/Livewire/Registration/SelectCountryCode.php
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
  resources/views/auth/registration/participant.blade.php
  resources/views/layouts/app.blade.php
  resources/views/livewire/registration/company-basic-form.blade.php
  resources/views/livewire/registration/company-representative-form.blade.php
  resources/views/livewire/registration/select-country-code.blade.php
  routes/web.php
  tests/Feature/CompanyControllerTest.php
Labels: bugfix, frontend

#501 Bugfix - Editions
  app/Console/Commands/UpsertMasterData.php
  app/Http/Controllers/Crew/EditionController.php
  app/Http/Controllers/Crew/EditionEventController.php
  app/Http/Controllers/RegistrationController.php
  app/Http/Middleware/EditionMiddleware.php
  app/Livewire/Edition/AddKeynoteModal.php
  app/Livewire/Edition/EditEditionModal.php
  app/Livewire/EditionEvent/EditEditionEventModal.php
  app/Livewire/Forms/EditionEventForm.php
  app/Livewire/Forms/EditionForm.php
  app/Livewire/Forms/KeynoteForm.php
  app/Models/Edition.php
  bootstrap/app.php
  database/migrations/2023_09_13_130057_create_editions_table.php
  database/migrations/2024_04_25_125646_create_events_table.php
  resources/views/components/sidemenus/content-moderator.blade.php
  resources/views/crew/editions/create.blade.php
  resources/views/crew/editions/index.blade.php
  resources/views/crew/editions/show.blade.php
  resources/views/livewire/edition-event/edit-edition-event-modal.blade.php
  resources/views/moderator/events/index.blade.php
  resources/views/welcome.blade.php
  routes/web.php
  tests/Feature/BoothControllerTest.php
  tests/Feature/CompanyControllerTest.php
  tests/Feature/PresentationControllerTest.php
  tests/Feature/RegistrationTest.php
  tests/Feature/RoomControllerTest.php
  tests/Feature/SponsorshipControllerTest.php
Labels: feature, high priority, frontend, backend, crew

#520 Bugfix - Profile page issues
  app/Http/Controllers/Crew/BoothController.php
  app/Http/Controllers/Crew/CompanyController.php
  app/Http/Controllers/Crew/PresentationController.php
  app/Http/Controllers/Crew/SponsorshipController.php
  app/Listeners/HandleFinalProgrammeReleased.php
  app/Livewire/EmailNotificationPreference.php
  app/Livewire/Schedule/PresentationModal.php
  app/Models/User.php
  config/fortify.php
  resources/views/livewire/email-notification-preference.blade.php
  resources/views/profile/show.blade.php
Labels: bugfix, participant

#522 Bugfix - Issues with requested entities
  app/Http/Controllers/Crew/BoothController.php
  app/Http/Controllers/Crew/PresentationController.php
  app/Http/Controllers/Crew/RoomController.php
  app/Livewire/Company/BoothRequest.php
  app/Livewire/Forms/BoothForm.php
  app/Livewire/Forms/PresentationForm.php
  app/Livewire/Forms/RoomForm.php
  app/Livewire/Presentation/EditPresentationModal.php
  app/Models/Company.php
  app/Models/Presentation.php
  resources/views/crew/booths/create.blade.php
  resources/views/crew/booths/show.blade.php
  resources/views/crew/companies/create.blade.php
  resources/views/crew/presentations/create.blade.php
  resources/views/crew/presentations/show.blade.php
  resources/views/crew/rooms/create.blade.php
  resources/views/crew/rooms/index.blade.php
  resources/views/livewire/booth/edit-booth-modal.blade.php
  resources/views/livewire/company/booth-request.blade.php
  resources/views/livewire/presentation/edit-presentation-modal.blade.php
  resources/views/livewire/room/edit-room-modal.blade.php
  resources/views/presentations/create.blade.php
  tests/Feature/BoothControllerTest.php
Labels: bugfix, frontend, backend
