Repository HZ-HBO-ICT/it-conference, pull requests merged in 2025-03, with the labels that each got.

#636 Documentation - ERD diagram XML
  erd.drawio.xml
Labels: documentation

#638 Documentation - Commonly used commands
  README.md
Labels: documentation

#640 Readded the roomseeder
  database/seeders/DatabaseSeeder.php
  database/seeders/InitialSeeder.php
  database/seeders/RoomSeeder.php
  phpstan-baseline.neon
Labels: bugfix, backend

#642 Feature - Proper state field
  app/Actions/Log/ApprovalHandler.php
  app/Console/Commands/ApproveLastCreatedCompany.php
  app/Enums/ApprovalStatus.php
  app/Http/Controllers/CompanyController.php
  app/Http/Controllers/Crew/BoothController.php
  app/Http/Controllers/Crew/CompanyController.php
  app/Http/Controllers/Crew/PresentationController.php
  app/Http/Controllers/Crew/SponsorshipController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/SpeakerController.php
  app/Livewire/Booth/CreateBooth.php
  app/Livewire/Company/SponsorshipRequest.php
  app/Livewire/Schedule/GridParentComponent.php
  app/Livewire/Schedule/PublishProgrammeButton.php
  app/Models/Booth.php
  app/Models/Company.php
  app/Models/DefaultPresentation.php
  app/Models/Difficulty.php
  app/Models/EditionEvent.php
  app/Models/Event.php
  app/Models/Feedback.php
  app/Models/FrequentQuestion.php
  app/Models/InternshipAttribute.php
  app/Models/Invitation.php
  app/Models/Presentation.php
  app/Models/Room.php
  app/Models/Sponsorship.php
  app/Models/Ticket.php
  app/Models/Timeslot.php
  app/Models/User.php
  app/Models/UserPresentation.php
  app/Traits/HasApprovalStatus.php
  app/View/Components/Dashboards/Crew.php
  database/factories/BoothFactory.php
  database/factories/CompanyFactory.php
  database/factories/PresentationFactory.php
  database/migrations/2024_03_25_161038_create_companies_table.php
  database/migrations/2024_03_25_162647_create_booths_table.php
  database/migrations/2024_03_26_094332_create_presentations_table.php
  database/seeders/CompanySeeder.php
  erd.drawio.xml
  phpstan-baseline.neon
  resources/views/components/dashboards/crew.blade.php
  resources/views/components/sidemenus/content-moderator.blade.php
  resources/views/livewire/booth/create-booth.blade.php
  resources/views/welcome.blade.php
  tests/Feature/BoothControllerTest.php
  tests/Feature/CompanyControllerTest.php
  tests/Feature/PresentationControllerTest.php
  tests/Feature/SponsorshipControllerTest.php
  tests/Unit/BoothTest.php
  tests/Unit/CompanyTest.php
  tests/Unit/PresentationTest.php
Labels: high priority, rework
