Repository HZ-HBO-ICT/it-conference, pull requests merged in 2025-07, with the labels that each got.

#687 Feature - Public frontend pages feedback
  app/Http/Controllers/SpeakerController.php
  app/Models/Sponsorship.php
  public/img/waitt25/logo.webp
  resources/css/app.css
  resources/views/components/waitt/dropdown-link.blade.php
  resources/views/components/waitt/dropdown.blade.php
  resources/views/components/waitt/nav-link.blade.php
  resources/views/components/waitt/responsive-nav-link.blade.php
  resources/views/components/waitt/tag.blade.php
  resources/views/contact.blade.php
  resources/views/faq.blade.php
  resources/views/layouts/app.blade.php
  resources/views/livewire/auth-navigation-menu.blade.php
  resources/views/livewire/guest-navigation-menu.blade.php
  resources/views/speakers/index.blade.php
  resources/views/speakers/show.blade.php
  resources/views/teams/public/index.blade.php
  resources/views/teams/public/show.blade.php
  resources/views/welcome.blade.php
  routes/web.php
  tailwind.config.js
Labels: high priority, frontend

#691 Add command that sets up the app for production
  app/Console/Commands/SetupProduction.php
Labels: production, backend

#695 Feature/#693 production setup wizard
  app/Console/Commands/SetupProduction.php
  composer.json
  composer.lock
Labels: feature, production, backend

#701 Fix links to TOS and Privacy Policy
  resources/views/auth/registration/participant.blade.php
Labels: bugfix

#697 Refactor 'create an admin' command
  app/Actions/Fortify/CreateNewUser.php
  app/Console/Commands/CreateAdmin.php
  phpstan-baseline.neon
  tests/Feature/RegistrationTest.php
  tests/Unit/CreateNewUserTest.php
Labels: feature, production, backend

#709 Bugfix - Unclear process in editions
  app/Livewire/Forms/EditionForm.php
  app/Models/Edition.php
  app/Models/Presentation.php
  database/migrations/2023_09_13_130057_create_editions_table.php
  database/seeders/ProgrammeReleasedSeeder.php
  phpstan-baseline.neon
  resources/views/crew/editions/create.blade.php
  resources/views/crew/editions/show.blade.php
  resources/views/livewire/edition/edit-edition-modal.blade.php
Labels: bugfix, backend, crew

#707 Bugfix - Badges and sponsorships on welcome page
  resources/views/welcome.blade.php
Labels: bugfix, frontend

#705 Rework - Auth pages redesign
  public/img/market-scaled.webp
  public/img/waitt25/dark-full-logo.png
  public/img/waitt25/light-full-logo.png
  resources/views/auth/login.blade.php
  resources/views/auth/registration-via-invitation.blade.php
  resources/views/auth/registration/company.blade.php
  resources/views/auth/registration/participant.blade.php
  resources/views/components/waitt/checkbox.blade.php
  resources/views/livewire/registration/company-basic-form.blade.php
  resources/views/livewire/registration/company-internships-form.blade.php
  resources/views/livewire/registration/company-location-form.blade.php
  resources/views/livewire/registration/company-motivation-form.blade.php
  resources/views/livewire/registration/company-representative-form.blade.php
  resources/views/livewire/registration/parent-component.blade.php
  resources/views/livewire/registration/select-country-code.blade.php
  resources/views/welcome.blade.php
Labels: frontend

#704 Frontend/#596 error pages
  resources/css/app.css
  resources/views/errors/401.blade.php
  resources/views/errors/402.blade.php
  resources/views/errors/403.blade.php
  resources/views/errors/404.blade.php
  resources/views/errors/419.blade.php
  resources/views/errors/429.blade.php
  resources/views/errors/500.blade.php
  resources/views/errors/503.blade.php
  resources/views/errors/minimal.blade.php
Labels: bugfix, frontend, ux

#713 Update favicon
  public/favicon.ico
  public/img/original.ico
  public/img/waitt25/favicon.png
  public/img/waitt25/favicon_2.png
Labels: feature

#719 Feature/#717 pending migrations
  app/Console/Commands/SetupProduction.php
Labels: feature, production, backend

#731 2025.2.2
  app/Livewire/Dashboards/Modals/CompanyDetailsModal.php
  app/Traits/FileValidation.php
  composer.json
  composer.lock
  config/livewire.php
  resources/views/livewire/dashboards/modals/company-details-modal.blade.php
  resources/views/teams/public/show.blade.php
  resources/views/welcome.blade.php
Labels: production
