Repository HZ-HBO-ICT/it-conference, pull requests merged in 2025-05, with the labels that each got.

#669 Maintenance - NPM dependencies
  composer.lock
  package-lock.json
Labels: bugfix, security

#668 Feature/659 contact us page design
  resources/views/contact.blade.php
Labels: frontend, rework

#653 Feature - Flexible presentation types
  app/Console/Commands/GenerateColoursSafelist.php
  app/Http/Controllers/Crew/PresentationController.php
  app/Http/Controllers/PresentationController.php
  app/Http/Requests/StorePresentationRequest.php
  app/Livewire/Forms/PresentationForm.php
  app/Livewire/Presentation/EditPresentationModal.php
  app/Livewire/PresentationType/CreateEditModal.php
  app/Livewire/PresentationType/DeleteModal.php
  app/Livewire/Schedule/GridParentComponent.php
  app/Livewire/Schedule/Presentation.php
  app/Models/Booth.php
  app/Models/Company.php
  app/Models/Edition.php
  app/Models/Presentation.php
  app/Models/PresentationType.php
  app/Policies/PresentationTypePolicy.php
  config/colours.php
  config/permissions/permissions.yml
  database/factories/PresentationFactory.php
  database/factories/PresentationTypeFactory.php
  database/factories/RoomFactory.php
  database/migrations/2024_03_01_142157_create_presentation_types_table.php
  database/migrations/2024_03_26_094332_create_presentations_table.php
  database/seeders/InitialSeeder.php
  database/seeders/PresentationTypeSeeder.php
  erd.drawio.xml
  package-lock.json
  phpstan-baseline.neon
  resources/views/crew/editions/show.blade.php
  resources/views/crew/presentations/create.blade.php
  resources/views/livewire/presentation-type/create-edit-modal.blade.php
  resources/views/livewire/presentation-type/delete-modal.blade.php
  resources/views/livewire/presentation/edit-presentation-modal.blade.php
  resources/views/livewire/schedule/grid-parent-component.blade.php
  resources/views/livewire/schedule/presentation.blade.php
  resources/views/presentations/create.blade.php
  tailwind.config.js
  tailwind.safelist.json
  tests/Feature/Console/GenerateColoursSafelistTest.php
  tests/Feature/Livewire/PresentationType/CreateEditModalTest.php
  tests/Feature/Livewire/PresentationType/DeleteModalTest.php
  tests/Feature/PresentationControllerTest.php
  tests/Unit/PresentationTest.php
  tests/Unit/PresentationTypeTest.php
  tests/Unit/UserTest.php
Labels: feature, rework, crew

#678 Bugfix - Left overs of static presentation types
  app/Http/Controllers/ProgrammeController.php
Labels: bugfix, frontend

#658 Feature - Default accounts for company rep and participant
  database/seeders/InitialSeeder.php
Labels: feature, backend
