Repository HZ-HBO-ICT/it-conference, pull requests merged in 2025-04, with the labels that each got.

#648 changed edition events to only be allowed within the 12 months before…
  app/Livewire/Forms/EditionEventForm.php
Labels: feature, bugfix, backend

#656 Maintenance - Npm vulnerability fix
  package-lock.json
Labels: security

#647 Feature - Programme released stage and setting up default opening/closing presentations
  app/Console/Commands/SetupStage.php
  database/seeders/InitialSeeder.php
  database/seeders/ProgrammeReleasedSeeder.php
Labels: backend

#657 Bugfix - Change event dates based on stage
  database/seeders/CompanyRegistrationSeeder.php
  database/seeders/ParticipantRegistrationSeeder.php
Labels: bugfix, backend
